server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/RANJEETJ06/ConfigSever.git"
          default-label: "master1.1"
          timeout: 5
          clone-on-start: true
          searchPaths: src/main/resources/config

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: 'adj97FBR7OreKVDlOsZywVZ7YAPEI6vf'

logging:
  level:
    pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"